export { default as Home } from './Home';
export { default as About } from './About';
export { default as HomeHero } from './HomeHero';
export { default as HomePreview } from './HomePreview';
export { default as Login } from './Login';
export { default as Dashboard } from './Dashboard';
export { default as Statistik } from './Statistik';
export { default as NotFound } from './NotFound';
export { default as Leaderboard } from './Leaderboard';